### ISSUE TITLE
Random bugs found during api testing

### ISSUE THREAD

**Issue by alchem0x2A** [beautiful-atoms/beautiful-atoms#149]
Below are a series of bugs found during testing the api schema. All the tests are based on commit `728113f2fb`. Some of them might have been resolved since then but I'll keep track anyway

in all cases, the `batoms` is the default CH4 molecule

- [x] Setting in `species` overwrite each other

Following code:
```
batoms.species["C"].color = [1, 0, 0, 1]
batoms.species["C"].material_style = "metallic"
```

Expected behavior: set the C atom with metallic material and red color

Actual behavior: setting `material_style` to "metallic" reset the color
```python
>>> batoms.species["C"].color
[0.5649999976158142, 0.5649999976158142, 0.5649999976158142, 1.0]
```

Exchange the order of `material_style` and `color` works but as long as `batoms.species.update()` is called, the color is again reset
```python
>>> batoms.species["C"].material_style = "metallic"
>>> batoms.species["C"].color = [1, 0, 0, 1]
>>> batoms.species["C"].color
[1.0, 0.0, 0.0, 1.0]
>>> batoms.species.update()
>>> batoms.species["C"].color
[0.5649999976158142, 0.5649999976158142, 0.5649999976158142, 1.0]
```

The behavior of the Species toolbar seems correct though

**Comment by alchem0x2A** [comment]
- [ ] Some properties not written to .blend file upon saving

General behavior: executing the script during one blender session works, but saved to .blend file and reload the batoms collection, some attributes restore to the default state. The mesh instances are not affected. 

The properties I have tested are:
- `batoms.boundary`
- `batoms.bonds.search_bond`
```python
>>> batoms.boundary
array([[-0.,  1.],
       [-0.,  1.],
       [-0.,  1.]])
>>> batoms.boundary = 0.1
>>> batoms.boundary
array([[-0.1       ,  1.10000002],
       [-0.1       ,  1.10000002],
       [-0.1       ,  1.10000002]])
>>> bpy.ops.wm.save_as_mainfile(filepath="/Users/ttian/ch4_bound.blend")
[Ignored outputs]
>>> bpy.ops.batoms.delete()
[Ignored outputs]
>>> bpy.ops.wm.open_mainfile(filepath="/Users/ttian/ch4_bound.blend")
>>> batoms = Batoms(label="CH4")
>>> batoms.boundary
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/batoms.py", line 1514, in boundary
    boundary = Boundary(self.label, boundary_datas=default_boundary_datas.copy(),
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/boundary.py", line 149, in __init__
    self.boundary = boundary
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/boundary.py", line 420, in boundary
    self.update()
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/boundary.py", line 362, in update
    boundary_list = search_boundary(images[f],
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/boundary.py", line 99, in search_boundary
    offsets[i0:i1] = np.append(
  File "<__array_function__ internals>", line 180, in append
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/python/lib/python3.10/site-packages/numpy/lib/function_base.py", line 5392, in append
    return concatenate((arr, values), axis=axis)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
```

@superstar54 if these issues are harder to fix than a general solution, we can keep as-is. This affects some of my api test scripts as I'm calling `batoms_api.render` and evaluate the saved blender file in another function, but can adapt to other ways of testing.

**Comment by alchem0x2A** [comment]
- [ ] Some properties may be outdated in `batoms` and need rewrite getter / setter
   - `batoms.bobj`
```python
>>> batom = CH4
>>> batoms.bobj
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/base/object.py", line 38, in bobj
    return self.get_bobj()
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/base/object.py", line 41, in get_bobj
    bobj = getattr(self.obj.batoms, self.bobj_name)
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/base/object.py", line 28, in obj
    return self.get_obj()
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/base/object.py", line 33, in get_obj
    raise KeyError('%s object is not exist.' % self.obj_name)
KeyError: 'batoms object is not exist.'
```

**Comment by alchem0x2A** [comment]
- [ ] Seg fault when updating `lattice_plane`

In some cases updating the settings in `lattice_plane` will cause blender to segfault.
MWE
```python
>>> atoms = bulk('Au', cubic=True)
>>> ba = Batoms(from_ase=atoms)
>>> ba.lattice_plane.setting[(1, 0, 0)] = {"distance": 1.0, "material_style": "metallic"}
# First call to the lattice_plane.draw() is fine
>>> ba.lattice_plane.draw()
# Updating the setting and call draw() will fail
>>> ba.lattice_plane.setting[(1, 0, 0)].color = [1.0, 0, 0, 1.0]
>>> ba.lattice_plane.draw()
Writing: /var/folders/q6/nnm9lfkd06s5jzm7psvk588w0000gn/T/blender.crash.txt
/opt/homebrew/bin/blender: line 2: 32669 Segmentation fault: 11  '/Users/ttian/Applications/Blender.app/Contents/MacOS/Blender' "$@"
```

This issue occurs on Blender 3.2 on Mac (arm), both gui and console are affected. `crystal_shape` is also having similar issues with the same root. @superstar54 maybe you could check if can reproduce on linux. Could be platform-specific issue

The crash text shows:
```bash
(miniforge3)--- tests/datas ‹develop› » cat /var/folders/q6/nnm9lfkd06s5jzm7psvk588w0000gn/T/blender.crash.txt                                    139 ↵
# Blender 3.2.0, Commit date: 2022-06-08 10:22, Hash e05e1e369187

# backtrace
0   Blender                             0x000000010c4a9aa8 BLI_system_backtrace + 56
1   Blender                             0x0000000104996cdc sig_handle_crash + 360
2   libsystem_platform.dylib            0x00000001aa5bd4c4 _sigtramp + 56
3   Blender                             0x00000001051dd4ac Collection_all_objects_next + 24
4   Blender                             0x0000000105353984 pyrna_prop_collection_iter_next + 44
5   Blender                             0x000000010c7ba2d8 _PyEval_EvalFrameDefault + 23652
6   Blender                             0x000000010c7b4578 _PyEval_Vector + 148
7   Blender                             0x000000010c7bd218 call_function + 428
8   Blender                             0x000000010c7ba8d0 _PyEval_EvalFrameDefault + 25180
9   Blender                             0x000000010c7b4578 _PyEval_Vector + 148
10  Blender                             0x000000010c7bd218 call_function + 428
11  Blender                             0x000000010c7ba820 _PyEval_EvalFrameDefault + 25004
12  Blender                             0x000000010c7b4578 _PyEval_Vector + 148
13  Blender                             0x000000010c7b44d0 PyEval_EvalCode + 108
14  Blender                             0x000000010c7b1198 builtin_exec + 668
15  Blender                             0x000000010c728f08 cfunction_vectorcall_FASTCALL + 232
16  Blender                             0x000000010c7bd218 call_function + 428
17  Blender                             0x000000010c7ba8d0 _PyEval_EvalFrameDefault + 25180
18  Blender                             0x000000010c7b4578 _PyEval_Vector + 148
19  Blender                             0x000000010c7bd218 call_function + 428
20  Blender                             0x000000010c7ba820 _PyEval_EvalFrameDefault + 25004
21  Blender                             0x000000010c7b4578 _PyEval_Vector + 148
22  Blender                             0x000000010c7bd218 call_function + 428
23  Blender                             0x000000010c7ba820 _PyEval_EvalFrameDefault + 25004
24  Blender                             0x000000010c7b4578 _PyEval_Vector + 148
25  Blender                             0x000000010c7bd218 call_function + 428
26  Blender                             0x000000010c7ba820 _PyEval_EvalFrameDefault + 25004
27  Blender                             0x000000010c7b4578 _PyEval_Vector + 148
28  Blender                             0x000000010c7bd218 call_function + 428
29  Blender                             0x000000010c7ba820 _PyEval_EvalFrameDefault + 25004
30  Blender                             0x000000010c7b4578 _PyEval_Vector + 148
31  Blender                             0x000000010c7bd218 call_function + 428
32  Blender                             0x000000010c7ba850 _PyEval_EvalFrameDefault + 25052
33  Blender                             0x000000010c7b4578 _PyEval_Vector + 148
34  Blender                             0x000000010c7b44d0 PyEval_EvalCode + 108
35  Blender                             0x000000010c800240 PyRun_StringFlags + 232
36  Blender                             0x0000000105343870 bpy_run_string_impl + 128
37  Blender                             0x00000001049960b4 arg_handle_python_console_run + 188
38  Blender                             0x000000010c3bff90 BLI_args_parse + 188
39  Blender                             0x0000000104993154 main + 796
40  dyld                                0x0000000116d39088 start + 516

# Python backtrace
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/utils/butils.py", line 182 in clean_coll_object_by_type
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/scripts/addons_contrib/batoms/lattice_plane/__init__.py", line 293 in draw
  File "<console>", line 1 in <module>
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/python/lib/python3.10/code.py", line 90 in runcode
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/python/lib/python3.10/code.py", line 64 in runsource
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/python/lib/python3.10/code.py", line 257 in push
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/python/lib/python3.10/code.py", line 214 in interact
  File "/Users/ttian/Applications/Blender.app/Contents/Resources/3.2/python/lib/python3.10/code.py", line 298 in interact
  File "<string>", line 1 in <module>
```
seems to be associated with `clean_coll_object_by_type`

**Comment by superstar54** [comment]
@alchem0x2A All the issues mentioned above are solved in the new PR #151. There could be other similar issues, I will check that later.

In #151, I re-organize the code a lot. Most of the parameters remain the same. But please test with the new batoms-api schema and see what we need to update.

The last one is platform-specific, and Blender does not crash on Ubuntu. This happened before, and it seems that we need to load the object before deleting it on Mac. I have fixed it. Now it should work on Mac, please test.

**Comment by alchem0x2A** [comment]
Thx! #150 is also working on my end. I'll do some initial tests with #151 and converge to a compatible api.

On the last point, updating the lattice plane still fails on blender 3.2 with main branch, but possibly an arm-build specific issue. Can ignore for now and make bug report to blender if necessary

**Comment by alchem0x2A** [comment]
Currently on #151 there is one test failing regarding ms but should be trivial.
```python
Error: Python: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ttian/Documents/Dev/beautiful-atoms-api/batoms_api/script_api.py", line 179, in run
    draw_list = apply_batoms_settings(batoms, settings)
  File "/Users/ttian/Documents/Dev/beautiful-atoms-api/batoms_api/script_api.py", line 135, in apply_batoms_settings
    modify(batoms, settings, schema, draw_list)
  File "/Users/ttian/Documents/Dev/beautiful-atoms-api/batoms_api/script_api.py", line 109, in modify
    sub_obj = getattr(obj, key)
AttributeError: 'Batoms' object has no attribute 'ms'
```
it looks good for the rest! nice work

**Comment by superstar54** [comment]
The `ms` plugin has been changed to `molecular_surface`. I just added the `ms` back with a deprecating warning.

**Comment by superstar54** [comment]
Does updating the lattice plane still fail on blender 3.2 with the `plugin` branch?

**Comment by alchem0x2A** [comment]
great! the lattice_planes and crystal_shape now works without crashing in blender 3.2 (both gui and console). can close the issue now
